### ISSUE TITLE
Whitpaper 

### ISSUE THREAD

**Issue by Lamoriasms** [coinchat/whitepaper#1]
Hi dreamcog 
Where  is your  white paper, and explain  where  you registered  on under  which  act

**Comment by greensea** [comment]
We are translating the whitpaper into English, there is no whilepaper in english.
We will post it while it's tranlated ASAP

**Comment by Lamoriasms** [comment]
How long time's  takes  for transaction,  You're  boss  denied  that  they haven't  Whit so why confused the users
